### ISSUE TITLE
oonib fails to start properly with latest Python package updates

### ISSUE THREAD

**Issue by kheops2713** [ooni/backend#107] opened 2017-04-22 01:12 UTC
Until last week, `oonib` worked perfectly fine after following the standard installation procedure, on an up-to-date Debian stable (Jessie):

1. create a Python 2 virtual environment
2. clone the repository
3. from the repository folder: `pip install -r requirements.txt`, `python setup.py install` and configure and run `python bin/oonib`

The list of installed packages in the Python virtual environment was (from `pip freeze`) (apart from `oonibackend`):

```
Automat==0.5.0
Parsley==1.3
PyYAML==3.12
Twisted==17.1.0
appdirs==1.4.3
argparse==1.2.1
asn1crypto==0.22.0
attrs==16.3.0
cffi==1.10.0
constantly==15.1.0
cryptography==1.8.1
cyclone==1.1
enum34==1.1.6
idna==2.5
incremental==16.10.1
ipaddr==2.1.11
ipaddress==1.0.18
packaging==16.8
pyOpenSSL==16.2.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
pygeoip==0.3.2
pyparsing==2.2.0
service-identity==16.0.0
six==1.10.0
txsocksx==1.15.0.2
txtorcon==0.18.0
wsgiref==0.1.2
zope.component==4.3.0
zope.event==4.2.0
zope.interface==4.3.3

```

Installing oonib on a new system and doing the same, just a few days later, led to `oonib` seemingly starting (in the foreground, the process was running), but yelling many errors in the logs, and not starting the tor process. The errors in the logs:

```
2017-04-22T02:36:32+0200 [-] Application starting on 60843
2017-04-22T02:36:32+0200 [cyclone.web.Application#info] Starting factory <cyclone.web.Application instance at 0x7fe08c1ef1b8>
2017-04-22T02:36:32+0200 [-] Noting that "/tmp/web_connectivity" does not exist; letting Tor create it.
2017-04-22T02:36:32+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallba
cks
            self._runCallbacks()
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1357, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbac
ks
            result = g.send(result)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/txtorcon/endpoints.py", line 427, in listen
            self.config.protocol.add_event_listener('INFO', info_event)
        exceptions.AttributeError: 'NoneType' object has no attribute 'add_event_listener'
        
2017-04-22T02:36:32+0200 [-] OONICollector starting on 44172
2017-04-22T02:36:32+0200 [oonib.api.OONICollector#info] Starting factory <oonib.api.OONICollector instance at 0x7fe08c135a28>
2017-04-22T02:36:32+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallba
cks
            self._runCallbacks()
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1357, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbac
ks
            result = g.send(result)
          File "/home/ooni/venvs/ooni-backend/local/lib/python2.7/site-packages/txtorcon/endpoints.py", line 427, in listen
            self.config.protocol.add_event_listener('INFO', info_event)
        exceptions.AttributeError: 'NoneType' object has no attribute 'add_event_listener'
        
2017-04-22T02:36:32+0200 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.RuntimeError: Tor exited with error-code 255

```
After forcing the Python packages back to the versions listed above, everything worked again.

The more recent Python package versions with which the error was thrown are:

```
Automat==0.5.0
PyYAML==3.12
Twisted==17.1.0
appdirs==1.4.3
argparse==1.2.1
asn1crypto==0.22.0
attrs==16.3.0
cffi==1.10.0
constantly==15.1.0
cryptography==1.8.1
cyclone==1.1
enum34==1.1.6
idna==2.5
incremental==16.10.1
ipaddr==2.1.11
ipaddress==1.0.18
packaging==16.8
pyOpenSSL==17.0.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
pygeoip==0.3.2
pyparsing==2.2.0
service-identity==16.0.0
six==1.10.0
txtorcon==0.19.0
wsgiref==0.1.2
zope.component==4.3.0
zope.event==4.2.0
zope.interface==4.4.0
```

Hope this helps!

**Comment by hellais** [comment] 2017-04-22 14:44
From the looks of the backtrace it seems like some txtorcon API changed between 0.18.0 and 0.19.0.
cc @meejah

**Comment by meejah** [comment] 2017-04-26 18:26
Hmm, I tried using the above instructions (`libdumbnet-dev` should be added to the apt-get line in the README) and it seems to work fine for me (using the provided example config); I get 3 hidden services started and no tracebacks in `oonib.log`. 

I tried with tor 0.2.9.10 and 0.3.1.0-alpha

Do I need to set any config options differently to see this?

**Comment by meejah** [comment] 2017-04-26 20:41
Okay, I released txtorcon 0.19.1 at least on PyPI, can you confirm if this is still an issue with that release or not? Thanks.

**Comment by anadahz** [comment] 2017-04-27 02:49
@kheops2713 I downgraded txtorcon to version `0.19.0` and cannot reproduce: https://github.com/TheTorProject/ooni-backend/issues/107#issue-223530395

Could you please provide a minimal example to reproduce your setup, such as an `oonib.conf` file ?

**Comment by bassosimone** [comment] 2017-09-26 11:30
@kheops2713 is this issue still happening or has it been fixed?

**Comment by bassosimone** [comment] 2020-09-25 07:49
Closing because oonib will be removed soon.

**Closed by bassosimone** 2020-09-25 07:49 UTC
Labels: ooni/backend
