### ISSUE TITLE
Add support for extracting middlebox test features

### ISSUE THREAD

**Issue by hellais** [ooni/backend#201] opened 2019-06-05 11:22 UTC
This is similar to https://github.com/ooni/pipeline/issues/200, but is for `http_invalid_request_line` & `http_header_field_manipulation` middlebox tests.

**Comment by FedericoCeratto** [comment] 2020-02-17 16:35
https://github.com/ooni/pipeline/blob/7f543468d673e66d4a94129a3342a08f552e8557/af/fastpath/fastpath/core.py#L585

**Comment by bassosimone** [comment] 2020-02-17 16:36
It seems HTTP Invalid Request Line is not yet implemented in the fast path

**Comment by FedericoCeratto** [comment] 2020-02-19 10:56
Duplicate of #307 , closing.

**Closed by FedericoCeratto** 2020-02-19 10:56 UTC
Labels: effort/S, ooni/pipeline, priority/low
